title: Charleston Real Estate Video Blog with Paul Kelton
description: Our mission is to be your best resource for Charleston real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, your professional Charleston Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Rental Map Guide
    url: https://rental-guide-kelton.paperform.co/
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Paul Kelton
  title: 
  license_number: Agent with Matt ONeill Real Estate<br>Co-Founder of Tide Property Management Co
  about_markdown: |
    Paul joined Matt O’Neill Real Estate in 2020 and specializes in investment sales in addition to sales in vacant land and multifamily sectors. He is currently pursuing his CCIM Designation.

    His primary focus entails multifamily sales and investment products, working side-by-side with owners, tenants, and buyers alike. He has also spearheaded numerous retail and land transactions. Paul’s commitment to providing his clients with the best possible results is directly related to his extensive and up-to-date market knowledge. Among other things, Paul’s ability to work consistently and diligently makes him an invaluable asset to the MORE Commercial team.

    Familiar with the history and charm of the Lowcountry, Paul spent a great amount of his childhood beachside at his family’s residence on Sullivan’s Island. He now lives on Daniel Island with his wife and two dogs.
  brand: Matt ONeill Real Estate
  brokerage:
  market: Charleston
  address: 1349 Old Georgetown Rd<br>Mt Pleasant, SC 29464
  phone: 843-460-3173
  phone_type:
  phone2:
  phone2_type:
  email: paul@paulchs.com
  url: https://paulchs.com

forms:
  sitekey:

CTAs:
  first_CTA_text: Free Property Value
  first_CTA_URL: /homevalue/
  second_CTA_text: Customized Market Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What is your Charleston property worth?"
    CTA_text: "Are you thinking of selling or interested in learning about prices in your neighborhood? We can help."
    CTA_link_text: "Free Property Value"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a property in Charleston?"
    CTA_text2: "Search the entire MLS"
    CTA_link_text2: "Customized Market Search"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
  google_business_url:

podcast:
  title: '-- market -- Real Estate Podcast with -- client name --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- client brand -- - your professional -- market -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- market --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- client name --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 35
  hero_text: 
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
  header_overlay: rgba(0, 0, 0, 0.3)

site_colors:
  brand_color: '#8a1c27'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
